# Generated by Django 5.1.4 on 2026-07-11 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type_notification', models.CharField(choices=[('NOUVELLE_RESERVATION', 'Nouvelle réservation'), ('NOUVELLE_COMMANDE', 'Nouvelle commande'), ('A_VALIDER', 'En attente de validation'), ('VALIDATION', 'Validation'), ('REFUS', 'Refus'), ('MODIFICATION', 'Modification demandée'), ('SORTIE', 'Sortie de stock'), ('ENTREE', 'Entrée de stock'), ('STOCK_FAIBLE', 'Stock faible / rupture'), ('GARANTIE_EXPIREE', 'Garantie expirée'), ('NOUVEAU_MATERIEL', 'Nouveau matériel'), ('INFO', 'Information')], default='INFO', max_length=30)),
                ('lien', models.CharField(blank=True, max_length=255)),
                ('lu', models.BooleanField(default=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-cree_le'],
            },
        ),
    ]
