# Generated by Django 5.1.4 on 2026-07-11 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('etape', models.CharField(choices=[('SOUMISSION', 'Soumission (employé / client)'), ('RESPONSABLE', 'Responsable hiérarchique'), ('MAGASINIER', 'Magasinier'), ('ADMINISTRATEUR', 'Administrateur'), ('VALIDATION_FINALE', 'Validation finale')], max_length=25)),
                ('decision', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Accepté'), ('REFUSE', 'Refusé'), ('MODIFICATION_DEMANDEE', 'Modification demandée')], default='EN_ATTENTE', max_length=25)),
                ('commentaire', models.TextField(blank=True)),
                ('date_traitement', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Étape de validation',
                'verbose_name_plural': 'Étapes de validation',
                'ordering': ['date_traitement'],
            },
        ),
    ]
