# Generated by Django 5.1.4 on 2026-07-11 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('niveau', models.CharField(choices=[('CATEGORIE', 'Catégorie'), ('SOUS_CATEGORIE', 'Sous-catégorie'), ('FAMILLE', 'Famille'), ('SOUS_FAMILLE', 'Sous-famille'), ('TYPE', 'Type'), ('CLASSE', 'Classe')], default='CATEGORIE', max_length=20)),
                ('masque', models.CharField(blank=True, help_text='Masque utilisé pour générer automatiquement la référence des matériels de ce nœud', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='catalog.categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['niveau', 'nom'],
                'unique_together': {('nom', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magasins', to='catalog.agence')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magasins_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'ordering': ['agence__nom', 'nom'],
                'unique_together': {('nom', 'agence')},
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=60, unique=True)),
                ('code_interne', models.CharField(max_length=60, unique=True)),
                ('code_barre', models.CharField(blank=True, max_length=60, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='materiels/qrcodes/')),
                ('code_barre_image', models.ImageField(blank=True, null=True, upload_to='materiels/codesbarres/')),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('marque', models.CharField(blank=True, max_length=100)),
                ('modele', models.CharField(blank=True, max_length=100)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('couleur', models.CharField(blank=True, max_length=50)),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('MOYEN', 'État moyen'), ('DEFECTUEUX', 'Défectueux'), ('HORS_SERVICE', 'Hors service'), ('REFORME', 'Réformé')], default='NEUF', max_length=20)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('garantie_fin', models.DateField(blank=True, null=True, verbose_name='Fin de garantie')),
                ('prix_achat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valeur', models.DecimalField(decimal_places=2, default=0, help_text='Valeur actuelle / comptable', max_digits=12)),
                ('quantite_disponible', models.PositiveIntegerField(default=0)),
                ('quantite_reservee', models.PositiveIntegerField(default=0)),
                ('quantite_commandee', models.PositiveIntegerField(default=0)),
                ('quantite_minimale', models.PositiveIntegerField(default=1)),
                ('quantite_maximale', models.PositiveIntegerField(default=100)),
                ('quantite_critique', models.PositiveIntegerField(default=2)),
                ('photo_principale', models.ImageField(blank=True, null=True, upload_to='materiels/photos/')),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiels', to='catalog.agence')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiels', to='catalog.categorie')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='catalog.fournisseur')),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiels', to='catalog.magasin')),
            ],
            options={
                'verbose_name': 'Matériel',
                'verbose_name_plural': 'Matériels',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='DocumentMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='materiels/documents/')),
                ('nom', models.CharField(max_length=150)),
                ('ajoute_le', models.DateTimeField(auto_now_add=True)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='catalog.materiel')),
            ],
            options={
                'verbose_name': 'Document de matériel',
                'verbose_name_plural': 'Documents de matériel',
            },
        ),
        migrations.CreateModel(
            name='PhotoMateriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='materiels/photos/')),
                ('legende', models.CharField(blank=True, max_length=150)),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='catalog.materiel')),
            ],
            options={
                'verbose_name': 'Photo de matériel',
                'verbose_name_plural': 'Photos de matériel',
            },
        ),
        migrations.AddIndex(
            model_name='materiel',
            index=models.Index(fields=['designation'], name='catalog_mat_designa_3cffce_idx'),
        ),
        migrations.AddIndex(
            model_name='materiel',
            index=models.Index(fields=['reference'], name='catalog_mat_referen_010dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='materiel',
            index=models.Index(fields=['numero_serie'], name='catalog_mat_numero__e7f4a5_idx'),
        ),
    ]
