# Generated by Django 5.1.4 on 2026-07-11 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='PLANIFIE', max_length=20)),
                ('date_planifiee', models.DateField()),
                ('date_realisation', models.DateTimeField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='catalog.magasin')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventaires_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date_planifiee'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('AJUSTEMENT', 'Ajustement'), ('INVENTAIRE', 'Inventaire (correction)')], max_length=20)),
                ('quantite', models.IntegerField(help_text='Positif pour une entrée, négatif pour une sortie')),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('reference_document', models.CharField(blank=True, help_text='N° bon, facture, réservation, etc.', max_length=100)),
                ('quantite_avant', models.IntegerField(default=0)),
                ('quantite_apres', models.IntegerField(default=0)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('magasin_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_entrants', to='catalog.magasin')),
                ('magasin_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_sortants', to='catalog.magasin')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='catalog.materiel')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_theorique', models.IntegerField()),
                ('quantite_comptee', models.IntegerField(blank=True, null=True)),
                ('ecart_justifie', models.TextField(blank=True)),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='stock.inventaire')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_inventaire', to='catalog.materiel')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
                'unique_together': {('inventaire', 'materiel')},
            },
        ),
    ]
