# Generated by Django 5.1.4 on 2026-07-11 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('VALIDATION', 'Validation'), ('REFUS', 'Refus'), ('ENTREE_STOCK', 'Entrée de stock'), ('SORTIE_STOCK', 'Sortie de stock'), ('RESERVATION', 'Réservation'), ('COMMANDE', 'Commande')], max_length=30)),
                ('modele', models.CharField(blank=True, help_text='Nom du modèle concerné', max_length=100)),
                ('objet_id', models.CharField(blank=True, max_length=50)),
                ('objet_repr', models.CharField(blank=True, max_length=255)),
                ('ancienne_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('navigateur', models.CharField(blank=True, max_length=255)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_activites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entrée du journal d'activité",
                'verbose_name_plural': 'Journal des activités',
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['action'], name='audit_journ_action_625b87_idx'), models.Index(fields=['modele'], name='audit_journ_modele_20ad34_idx'), models.Index(fields=['horodatage'], name='audit_journ_horodat_235c88_idx')],
            },
        ),
    ]
