# Generated by Django 6.0.7 on 2026-07-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('Ordinateurs', 'Ordinateurs'), ('Serveurs', 'Serveurs'), ('Réseau', 'Réseau'), ('Switch', 'Switch'), ('Routeur', 'Routeur'), ('Firewall', 'Firewall'), ('Cybersécurité', 'Cybersécurité'), ('Logiciels', 'Logiciels'), ('Licences', 'Licences'), ('Mobilier', 'Mobilier'), ('Téléphonie', 'Téléphonie'), ('Caméras', 'Caméras'), ('Onduleurs', 'Onduleurs'), ('Stockage', 'Stockage'), ('Fibre Optique', 'Fibre Optique'), ('Câblage', 'Câblage'), ('Consommables', 'Consommables'), ('Outillage', 'Outillage'), ('Électricité', 'Électricité'), ('Audiovisuel', 'Audiovisuel')], max_length=50)),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('modele', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('fournisseur', models.CharField(blank=True, max_length=150, null=True)),
                ('quantite_dispo', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=5)),
                ('quantite_reservee', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueFlux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('Création', 'Création'), ('Modification', 'Modification'), ('Entrée', 'Entrée'), ('Sortie', 'Sortie'), ('Réservation', 'Réservation'), ('Libération', 'Libération'), ('Suppression', 'Suppression')], max_length=20)),
                ('message', models.TextField()),
                ('date_action', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
