# Generated by Django 5.1.4 on 2026-07-11 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon (panier)'), ('EN_ATTENTE', 'En attente de validation'), ('MODIFICATION_DEMANDEE', 'Modification demandée'), ('VALIDE', 'Validée'), ('REFUSE', 'Refusée'), ('ANNULE', 'Annulée')], default='BROUILLON', max_length=25)),
                ('etape_courante', models.CharField(choices=[('SOUMISSION', 'Soumission (employé / client)'), ('RESPONSABLE', 'Responsable hiérarchique'), ('MAGASINIER', 'Magasinier'), ('ADMINISTRATEUR', 'Administrateur'), ('VALIDATION_FINALE', 'Validation finale')], default='SOUMISSION', max_length=25)),
                ('commentaire_demandeur', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('soumise_le', models.DateTimeField(blank=True, null=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_commande', to='catalog.materiel')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
                'unique_together': {('commande', 'materiel')},
            },
        ),
    ]
